const TIME_LIMIT_MS=10000, QUESTIONS_PER_SESSION=15, STORAGE_KEY="adaptive_writing_v1";
const $=id=>document.getElementById(id), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let audioCtx=null,timerHandle=null,deadline=0,locked=false,current=null,session=null,soundOn=true,lastTickShown=11;
function hashId(text){let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return "chunk_"+(h>>>0).toString(36)}
function compileContent(){const chunks={},sentences=[];let n=1;for(const p of WRITING_CONTENT.patterns){const items=WRITING_CONTENT.sets[p.set];for(const item of items){const texts=[...p.en,...item.en],ids=texts.map(t=>{const id=hashId(t.toLowerCase());if(!chunks[id])chunks[id]={id:id,text:t,family:p.family,level:p.level,tags:["writing","reusable"],compatibleTopics:[item.t],difficulty:p.level==="C1"?75:p.level==="B2+"?55:35};else if(!chunks[id].compatibleTopics.includes(item.t))chunks[id].compatibleTopics.push(item.t);return id});let en=texts.join(" ").replace(/\s+([,.;!?])/g,"$1");if(!/[.!?]$/.test(en))en+=".";let es=(p.es+" "+item.es).replace(/\s+([,.;!?])/g,"$1");if(!/[.!?]$/.test(es))es+=".";sentences.push({id:"sentence_"+String(n++).padStart(3,"0"),patternId:p.id,spanish:es,english:en,chunkIds:ids,level:p.level,topics:[item.t],functions:[p.family],difficulty:p.level==="C1"?75:p.level==="B2+"?55:35,priority:100,canonical:true,source:"curated"})}}return {chunks:Object.values(chunks),sentences:sentences}}
const CONTENT=compileContent(), CHUNKS=Object.fromEntries(CONTENT.chunks.map(x=>[x.id,x])), BANK=CONTENT.sentences;
function freshState(){return {schemaVersion:1,contentVersion:WRITING_CONTENT.contentVersion,level:1,xp:0,rating:50,streak:0,totalSessions:0,totalAnswers:0,totalCorrect:0,sentenceStats:{},chunkStats:{},history:[],sessionHistory:[]}}
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));return s&&s.schemaVersion===1?Object.assign(freshState(),s):freshState()}catch(e){return freshState()}}
let state=loadState(); function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function getStat(map,id){return map[id]||(map[id]={seen:0,correct:0,incorrect:0,totalMs:0,mastery:0,stability:0,lastSeenAt:null,dueAt:null,lastCorrect:null,successSessions:0,lastSuccessLevel:null,spacedWins:0})}
function calcMastery(st){if(!st.seen)return 0;const acc=st.correct/st.seen,exposure=Math.min(1,st.seen/8),avg=st.totalMs/st.seen,speed=clamp(1-avg/TIME_LIMIT_MS,0,1),sessions=Math.min(1,(st.successSessions||0)/5),spaced=Math.min(1,(st.spacedWins||0)/3);return Math.round((acc*.35+exposure*.15+speed*.15+sessions*.20+spaced*.15)*100)}
function masteryStage(m){return m>=85?"DURABLE":m>=70?"AUTOMATIC":m>=50?"SECURE":m>=25?"FAMILIAR":m>0?"SEEN":"NEW"}
function refreshRating(){const r=state.history.slice(-100);if(!r.length){state.rating=50;return}const acc=r.filter(x=>x.correct).length/r.length,avg=r.reduce((a,b)=>a+b.responseMs,0)/r.length,speed=clamp(1-avg/TIME_LIMIT_MS,0,1),vals=CONTENT.chunks.map(c=>getStat(state.chunkStats,c.id).mastery),m=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length/100:0;state.rating=Math.round((acc*.45+speed*.25+m*.30)*100)}
function overall(){const seen=Object.values(state.sentenceStats).filter(x=>x.seen>0).length,recent=state.history.slice(-100),acc=recent.length?recent.filter(x=>x.correct).length/recent.length:0,avg=recent.length?recent.reduce((a,b)=>a+b.responseMs,0)/recent.length:0,sm=Object.values(state.sentenceStats),mastery=sm.length?sm.reduce((a,b)=>a+(b.mastery||0),0)/sm.length:0,cm=Object.values(state.chunkStats),chunksMastered=cm.filter(x=>(x.mastery||0)>=85).length;return {coverage:seen/BANK.length,seen:seen,acc:acc,avg:avg,mastery:mastery,chunksMastered:chunksMastered}}
function applyTheme(){const ranks=(window.ADRIAN_VISUAL_SYSTEM&&window.ADRIAN_VISUAL_SYSTEM.ranks)||[],rank=clamp(Math.ceil((state.rating||1)/100*15),1,15),r=ranks[rank-1];if(r){document.documentElement.style.setProperty("--ambient",r.surface);document.documentElement.style.setProperty("--accent",r.color);document.documentElement.style.setProperty("--accentText",r.text)}$("rankName").textContent=r?r.name.toUpperCase()+" · R"+rank:"R"+rank}
function sentenceWeight(s){const st=getStat(state.sentenceStats,s.id),weak=Math.min.apply(null,s.chunkIds.map(id=>getStat(state.chunkStats,id).mastery)),unseen=st.seen===0?1.35:1,recentError=st.lastCorrect===false?2.2:1,mastered=st.mastery>=90?.55:1,due=st.dueAt&&Date.parse(st.dueAt)<=Date.now()?2:1;return (1+(100-weak)/100*2.4)*unseen*recentError*mastered*due}
function weightedPick(pool){let total=pool.reduce((a,s)=>a+sentenceWeight(s),0),r=Math.random()*total;for(const s of pool){r-=sentenceWeight(s);if(r<=0)return s}return pool[pool.length-1]}
function takeWeighted(pool,n,out){for(let k=0;k<n&&pool.length;k++){const s=weightedPick(pool),i=pool.indexOf(s);out.push(s);pool.splice(i,1)}}
function buildPlan(){const out=[],used=new Set(),now=Date.now();const choose=(filter,n)=>{const pool=BANK.filter(s=>!used.has(s.id)&&filter(s));const picked=[];takeWeighted(pool,n,picked);picked.forEach(s=>{out.push(s);used.add(s.id)})};choose(s=>{const st=getStat(state.sentenceStats,s.id);return st.seen>0&&st.dueAt&&Date.parse(st.dueAt)<=now},5);choose(s=>{const st=getStat(state.sentenceStats,s.id);return st.seen>0&&st.mastery<70},5);choose(s=>getStat(state.sentenceStats,s.id).seen===0,3);choose(()=>true,QUESTIONS_PER_SESSION-out.length);return shuffle(out)}
function distractorIds(sentence){return[]}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}if(a.length>1&&a.every((x,i)=>x===arr[i]))[a[0],a[1]]=[a[1],a[0]];return a}
async function ensureAudio(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!audioCtx)audioCtx=new AC();if(audioCtx.state==="suspended")await audioCtx.resume();return audioCtx.state==="running"}catch(e){return false}}
function tone(freq,dur=.035,gain=.018,type="sine",delay=0){if(!soundOn||!audioCtx||audioCtx.state!=="running")return;const t=audioCtx.currentTime+delay,o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0002,gain),t+.004);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+dur+.01)}
function playTick(strong=false,step=0){const f=strong?(step%2?1540:1260):(step%2?1280:980);tone(f,strong?.034:.026,strong?.026:.016,"square")}
const NOTE_FREQ=[220,261.63,293.66,329.63,392,440,523.25];
function playTap(pos){tone(NOTE_FREQ[Math.min(pos,NOTE_FREQ.length-1)],.055,.018,"sine")}
function playCorrect(){tone(523.25,.065,.030,"sine");tone(659.25,.075,.026,"triangle",.042);tone(783.99,.105,.024,"sine",.095)}
function playWrong(){tone(330,.065,.020,"triangle");tone(247,.090,.018,"sine",.055)}
function playComplete(){tone(392,.075,.022,"sine");tone(523.25,.085,.024,"triangle",.070);tone(659.25,.100,.026,"sine",.145);tone(783.99,.155,.028,"sine",.230)}
function refreshSoundButton(){const b=$("soundBtn");if(b){b.textContent=soundOn?"🔊":"🔇";b.setAttribute("aria-label",soundOn?"Sound on":"Sound off")}}
function displayChunk(id){return CHUNKS[id].text.toLocaleLowerCase("en")}
function show(id){["startScreen","gameScreen","endScreen","reviewScreen"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function renderStart(){refreshRating();applyTheme();const o=overall();$("levelText").textContent="LEVEL "+state.level;$("coverageText").textContent=o.seen+" / "+BANK.length;$("coverageFill").style.width=(o.coverage*100)+"%";$("masteryText").textContent=Math.round(o.mastery)+"%";$("masteryFill").style.width=o.mastery+"%";$("ratingText").textContent=state.rating;$("accuracyText").textContent=o.acc?Math.round(o.acc*100)+"%":"—";$("avgText").textContent=o.avg?(o.avg/1000).toFixed(1)+"s":"—";$("answersText").textContent=state.totalAnswers;$("chunksText").textContent=o.chunksMastered+"/"+CONTENT.chunks.length;renderLeague()}
function renderLeague(){const rows=CONTENT.chunks.map(c=>({c:c,st:getStat(state.chunkStats,c.id)})).filter(x=>x.st.seen>=2).sort((a,b)=>b.st.mastery-a.st.mastery||b.st.seen-a.st.seen).slice(0,8);$("league").innerHTML=rows.length?rows.map((x,i)=>'<div class="leagueRow"><span>'+(i+1)+'. '+esc(x.c.text)+'</span><b>'+x.st.mastery+' <small>'+masteryStage(x.st.mastery)+'</small></b></div>').join(""):'<div class="empty">The chunk league appears after a few rounds.</div>'}
function startSession(){ensureAudio();session={level:state.level,index:0,correct:0,times:[],records:[],plan:buildPlan()};$("sessionLevel").textContent="L"+state.level;show("gameScreen");nextQuestion()}
function renderSegments(left){[...$("segments").children].forEach((e,i)=>e.classList.toggle("on",i<Math.ceil(left)))}
function startTimer(){clearInterval(timerHandle);deadline=performance.now()+TIME_LIMIT_MS;lastTickShown=11;timerHandle=setInterval(()=>{const left=Math.max(0,(deadline-performance.now())/1000),shown=Math.ceil(left);$("timerText").textContent=left.toFixed(1);$("timer").style.setProperty("--timer-cut",(100-left/(TIME_LIMIT_MS/1000)*100)+"%");renderSegments(left);if(shown<lastTickShown&&shown>0&&shown<10){playTick(shown<=3,shown);lastTickShown=shown}if(left<=0){clearInterval(timerHandle);submitAnswer(true)}},50)}
function nextQuestion(){locked=false;if(session.index>=session.plan.length){finishSession();return}const base=session.plan[session.index];current=Object.assign({},base,{selected:[],distractorIds:[],display:shuffle(base.chunkIds)});$("qIndex").textContent=session.index+1;$("qTotal").textContent="/ "+session.plan.length;renderBuild();const wrap=$("chunks");wrap.innerHTML="";current.display.forEach(id=>{const b=document.createElement("button");b.className="chunk";b.dataset.id=id;b.textContent=displayChunk(id);b.onclick=()=>selectChunk(id,b);wrap.appendChild(b)});$("timerText").textContent="10.0";renderSegments(10);startTimer()}
function selectChunk(id,button){if(locked||button.disabled)return;ensureAudio();button.disabled=true;button.classList.add("used");current.selected.push(id);playTap(current.selected.length-1);renderBuild();if(current.selected.length===current.chunkIds.length)submitAnswer(false)}
function renderBuild(correctView=false){const area=$("buildArea");area.innerHTML="";const ids=correctView?current.chunkIds:current.selected,total=current.chunkIds.length;for(let i=0;i<total;i++){const row=document.createElement("div");row.className="slotRow";const num=document.createElement("div");num.className="slotNum";num.textContent=String(i+1);row.appendChild(num);const id=ids[i];if(id){const b=document.createElement(correctView?"div":"button");b.className="built"+(correctView?" static":"");const ranks=ADRIAN_VISUAL_SYSTEM.ranks,rank=[1,4,7,10,13,15][Math.min(i,5)],r=ranks[rank-1];b.style.background=r.band;b.style.borderColor=r.color;b.style.color="#fff";b.textContent=displayChunk(id);if(!correctView){b.title="Tap to undo";b.onclick=()=>undoChunk(i)}row.appendChild(b)}else{const empty=document.createElement("div");empty.className="slotEmpty";empty.textContent="…";row.appendChild(empty)}area.appendChild(row)}}
function undoChunk(i){if(locked)return;const id=current.selected.splice(i,1)[0],btn=[...$("chunks").children].find(x=>x.dataset.id===id&&x.disabled);if(btn){btn.disabled=false;btn.classList.remove("used")}renderBuild()}
function compare(selected,correct){return correct.map((id,i)=>({chunkId:id,correctPosition:i,selectedPosition:selected.indexOf(id),correct:selected[i]===id}))}
function updateStats(sentence,ok,ms,results){const nowMs=Date.now(),now=new Date(nowMs).toISOString(),ss=getStat(state.sentenceStats,sentence.id),previousSeen=ss.lastSeenAt?Date.parse(ss.lastSeenAt):null;ss.seen++;ss[ok?"correct":"incorrect"]++;ss.totalMs+=ms;if(ok){if(ss.lastSuccessLevel!==state.level){ss.successSessions=(ss.successSessions||0)+1;ss.lastSuccessLevel=state.level}if(previousSeen&&nowMs-previousSeen>=18*3600000)ss.spacedWins=(ss.spacedWins||0)+1}ss.lastSeenAt=now;ss.lastCorrect=ok;ss.stability=clamp((ss.stability||0)+(ok?8:-12),0,100);ss.mastery=calcMastery(ss);const sentenceDays=ok?(ss.mastery<50?.25:ss.mastery<70?.75:ss.mastery<85?2:5):.01;ss.dueAt=new Date(nowMs+sentenceDays*86400000).toISOString();for(const r of results){const cs=getStat(state.chunkStats,r.chunkId),chunkPrevious=cs.lastSeenAt?Date.parse(cs.lastSeenAt):null;cs.seen++;cs[r.correct?"correct":"incorrect"]++;cs.totalMs+=ms;if(r.correct){if(cs.lastSuccessLevel!==state.level){cs.successSessions=(cs.successSessions||0)+1;cs.lastSuccessLevel=state.level}if(chunkPrevious&&nowMs-chunkPrevious>=18*3600000)cs.spacedWins=(cs.spacedWins||0)+1}cs.lastSeenAt=now;cs.lastCorrect=r.correct;cs.stability=clamp((cs.stability||0)+(r.correct?8:-12),0,100);cs.mastery=calcMastery(cs);const chunkDays=r.correct?(cs.mastery<50?.25:cs.mastery<70?.75:cs.mastery<85?2:5):.01;cs.dueAt=new Date(nowMs+chunkDays*86400000).toISOString()}}
function submitAnswer(timeout){if(locked)return;locked=true;clearInterval(timerHandle);const ms=timeout?TIME_LIMIT_MS:Math.max(50,TIME_LIMIT_MS-(deadline-performance.now())),selected=[...current.selected],correct=current.chunkIds,ok=!timeout&&selected.length===correct.length&&selected.every((id,i)=>id===correct[i]),results=compare(selected,correct);updateStats(current,ok,Math.round(ms),results);state.totalAnswers++;if(ok)state.totalCorrect++;state.streak=ok?state.streak+1:0;state.xp+=ok?Math.max(10,Math.round(35-ms/400)):2;const rec={id:"attempt_"+Date.now(),sessionLevel:session.level,sentenceId:current.id,presentedChunkIds:current.display,selectedChunkIds:selected,correctChunkIds:correct,correct:ok,responseMs:Math.round(ms),timeLimitMs:TIME_LIMIT_MS,timedOut:timeout,chunkResults:results,createdAt:new Date().toISOString()};state.history.push(rec);state.history=state.history.slice(-5000);session.records.push(rec);session.times.push(ms);if(ok)session.correct++;refreshRating();save();feedback(ok,ms,timeout);setTimeout(()=>{session.index++;nextQuestion()},ok?480:1500)}
function feedback(ok,ms,timeout){const f=$("feedback");f.className="feedback "+(ok?"ok":"bad")+" show";f.innerHTML=ok?'CORRECT <small>'+(ms/1000).toFixed(2)+'s</small>':(timeout?"TIME":"INCORRECT");if(ok)playCorrect();else{playWrong();renderBuild(true)}setTimeout(()=>f.classList.remove("show"),ok?430:1350)}
function finishSession(){clearInterval(timerHandle);const total=session.records.length,acc=total?session.correct/total:0,avg=total?Math.round(session.times.reduce((a,b)=>a+b,0)/total):0;state.totalSessions++;state.level++;state.sessionHistory.push({level:session.level,correct:session.correct,total:total,accuracy:acc,avgMs:avg,rating:state.rating,ts:Date.now()});state.sessionHistory=state.sessionHistory.slice(-1000);save();playComplete();renderEnd(acc,avg);show("endScreen")}
function renderEnd(acc,avg){applyTheme();$("endScore").textContent=session.correct+"/"+session.records.length;$("endAccuracy").textContent=Math.round(acc*100)+"%";$("endAvg").textContent=(avg/1000).toFixed(1)+"s";$("endRating").textContent=state.rating;$("playAgainBtn").textContent="CONTINUE · LEVEL "+state.level;const wrong=session.records.filter(r=>!r.correct);$("reviewBtn").disabled=wrong.length===0;$("reviewBtn").textContent=wrong.length?"REVIEW ERRORS · "+wrong.length:"REVIEW ERRORS"}
function renderReview(){const wrong=session?session.records.filter(r=>!r.correct):[];$("errorsList").innerHTML=wrong.length?wrong.map((r,i)=>{const s=BANK.find(x=>x.id===r.sentenceId);return '<div class="reviewItem"><b>ERROR '+(i+1)+' · '+((r.responseMs||0)/1000).toFixed(1)+'s</b><p>'+esc(s?s.english.toLocaleLowerCase("en"):"")+"</p></div>"}).join(""):'<div class="empty">No errors in this level.</div>';show("reviewScreen")}
function exportProgress(){const payload={app:"adaptive-writing",schemaVersion:1,contentVersion:WRITING_CONTENT.contentVersion,exportedAt:new Date().toISOString(),state:state},a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="adaptive-writing-progress-"+new Date().toISOString().slice(0,10)+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importProgress(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.app!=="adaptive-writing"||x.schemaVersion!==1)throw Error("bad");state=Object.assign(freshState(),x.state);save();renderStart();alert("Progress imported.")}catch(e){alert("Invalid Adaptive Writing progress file.")}};r.readAsText(file)}
function resetProgress(){if(confirm("Reset all Adaptive Writing progress?")){state=freshState();save();renderStart()}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function exitToMenu(){clearInterval(timerHandle);locked=true;session=null;current=null;renderStart();show("startScreen")}
function boot(){if(BANK.length!==300)throw Error("Expected 300 sentences, found "+BANK.length);const seg=$("segments");for(let i=0;i<10;i++){const d=document.createElement("div");d.className="seg";seg.appendChild(d)}$("startBtn").onclick=async()=>{await ensureAudio();startSession()};$("continueBtn").onclick=()=>{renderStart();show("startScreen")};$("playAgainBtn").onclick=async()=>{await ensureAudio();startSession()};$("reviewBtn").onclick=renderReview;$("reviewBackBtn").onclick=()=>show("endScreen");$("soundBtn").onclick=async()=>{soundOn=!soundOn;if(soundOn){await ensureAudio();tone(760,.06,.025,"sine")}refreshSoundButton()};$("exitBtn").onclick=exitToMenu;$("exportBtn").onclick=exportProgress;$("importBtn").onclick=()=>$("importFile").click();$("importFile").onchange=e=>e.target.files[0]&&importProgress(e.target.files[0]);$("resetBtn").onclick=resetProgress;refreshSoundButton();renderStart();show("startScreen")}
boot();